### ISSUE TITLE
TPM MVP 1

### ISSUE THREAD

**Issue by oddcoder** [tpm-rs/tpm-rs#121]
- [ ] [Add test that forbids panic symbols in the compiled binary](https://github.com/tpm-rs/tpm-rs/issues/42)
- [ ] [Add TPM_GetRandom Command on client side.](https://github.com/tpm-rs/tpm-rs/issues/118)
- [ ] [Add TPM_GetRandom Command on server side](https://github.com/tpm-rs/tpm-rs/issues/119)
- [ ] [Create SWTPM](https://github.com/tpm-rs/tpm-rs/issues/120)
